#!/usr/bin/env zsh
# Sparkdock Shell Completions — fallback generator
#
# Completion files are generated by Ansible at install/upgrade time.
# If a completion file is missing (e.g. manual install outside Ansible),
# this script generates it as a fallback. Registration is handled by
# the autoload+compdef loop in sparkdock.zshrc (runs after this file).

# AI tool completions
if command_exists opencode; then
  _opencode_completion_file="${HOME}/.local/share/zsh/site-functions/_opencode"
  if [[ ! -f "${_opencode_completion_file}" ]]; then
    mkdir -p "${HOME}/.local/share/zsh/site-functions"
    opencode completion > "${_opencode_completion_file}" 2>/dev/null || rm -f "${_opencode_completion_file}"
  fi
fi

if command_exists openspec; then
  _openspec_completion_file="${HOME}/.local/share/zsh/site-functions/_openspec"
  if [[ ! -f "${_openspec_completion_file}" ]]; then
    mkdir -p "${HOME}/.local/share/zsh/site-functions"
    openspec completion generate zsh > "${_openspec_completion_file}" 2>/dev/null || rm -f "${_openspec_completion_file}"
  fi
fi
