#!/usr/bin/env zsh
# Sparkdock Shell Completions
# This file configures modern shell command completions for an enhanced, discoverable CLI experience
#
# Completion files are generated by Ansible at install/upgrade time.
# If a completion file is missing (e.g. manual install outside Ansible), it is generated as a fallback.

# Helper function to check if a command exists
command_exists() {
  command -v "$1" &> /dev/null
}

# AI tool completions
# Completion files are managed by Ansible (regenerated on every install/upgrade).
if command_exists opencode; then
  _opencode_completion_file="${HOME}/.local/share/zsh/site-functions/_opencode"
  if [[ ! -f "${_opencode_completion_file}" ]]; then
    mkdir -p "${HOME}/.local/share/zsh/site-functions"
    opencode completion > "${_opencode_completion_file}" 2>/dev/null || rm -f "${_opencode_completion_file}"
  fi
  if [[ -f "${_opencode_completion_file}" ]]; then
    source "${_opencode_completion_file}"
  fi
fi

if command_exists openspec; then
  _openspec_completion_file="${HOME}/.local/share/zsh/site-functions/_openspec"
  if [[ ! -f "${_openspec_completion_file}" ]]; then
    mkdir -p "${HOME}/.local/share/zsh/site-functions"
    openspec completion generate zsh > "${_openspec_completion_file}" 2>/dev/null || rm -f "${_openspec_completion_file}"
  fi
  if [[ -f "${_openspec_completion_file}" ]]; then
    source "${_openspec_completion_file}"
  fi
fi
