---
cask_packages:
  - applite
  - font-droid-sans-mono-nerd-font
  - font-inconsolata-nerd-font
  - font-fira-code-nerd-font
  - google-chrome
  - ghostty
  - iterm2
  - maccy
  - cameracontroller
  - visual-studio-code
  - slack
  - zoom
  - monitorcontrol
