# Package metadata for catalog display
# Format: package_name: { category: "...", description: "..." }

# Cask Packages (GUI Applications)
docker-desktop:
  category: "Container Tools"
  description: "Docker Desktop - Container development platform"

google-cloud-sdk:
  category: "Cloud Tools"
  description: "Google Cloud SDK - Command-line tools for Google Cloud Platform"

applite:
  category: "System Utilities"
  description: "ApplitE - Third-party app installer for macOS"

font-droid-sans-mono-nerd-font:
  category: "Fonts"
  description: "Droid Sans Mono Nerd Font - Developer font with icons"

font-inconsolata-nerd-font:
  category: "Fonts"
  description: "Inconsolata Nerd Font - Monospace font with icons"

font-fira-code-nerd-font:
  category: "Fonts"
  description: "Fira Code Nerd Font - Monospace font with ligatures"

google-chrome:
  category: "Browsers"
  description: "Google Chrome - Web browser"

ghostty:
  category: "Terminal Emulators"
  description: "Ghostty - Fast, native terminal emulator"

git-credential-manager:
  category: "Development Tools"
  description: "Git Credential Manager - Secure Git credential storage"

iterm2:
  category: "Terminal Emulators"
  description: "iTerm2 - Advanced terminal emulator for macOS"

maccy:
  category: "Productivity"
  description: "Maccy - Clipboard manager"

cameracontroller:
  category: "System Utilities"
  description: "Camera Controller - Control external camera settings"

visual-studio-code:
  category: "Code Editors"
  description: "Visual Studio Code - Code editor with extensions"

slack:
  category: "Communication"
  description: "Slack - Team communication platform"

zoom:
  category: "Communication"
  description: "Zoom - Video conferencing application"

monitorcontrol:
  category: "System Utilities"
  description: "MonitorControl - Control external monitor brightness and volume"

# Homebrew Packages (Command-line Tools)
awscli:
  category: "Cloud Tools"
  description: "AWS CLI - Amazon Web Services command line interface"

eza:
  category: "Shell Utilities"
  description: "eza - Modern replacement for ls with colors and icons"

docker-credential-helper-ecr:
  category: "Cloud Tools"
  description: "Docker Credential Helper ECR - AWS ECR authentication"

kubernetes-cli:
  category: "Container Tools"
  description: "kubectl - Kubernetes command line tool"

k9s:
  category: "Container Tools"
  description: "k9s - Terminal UI for Kubernetes cluster management"

kind:
  category: "Container Tools"
  description: "kind - Kubernetes in Docker for local clusters"

kubectx:
  category: "Container Tools"
  description: "kubectx - Fast way to switch Kubernetes contexts"

skaffold:
  category: "Container Tools"
  description: "Skaffold - Local Kubernetes development tool"

stern:
  category: "Container Tools"
  description: "Stern - Multi-pod log tailing for Kubernetes"

lima:
  category: "Container Tools"
  description: "Lima - Linux virtual machines for macOS"

atuin:
  category: "Shell Utilities"
  description: "Atuin - Shell history sync and search"

bc:
  category: "System Utilities"
  description: "bc - Arbitrary precision calculator"

btop:
  category: "System Monitoring"
  description: "btop - Resource monitor with terminal UI"

fastfetch:
  category: "System Monitoring"
  description: "fastfetch - System information tool"

gnupg:
  category: "Security"
  description: "GnuPG - GNU Privacy Guard for encryption"

jless:
  category: "Text Processing"
  description: "jless - JSON viewer for terminal"

just:
  category: "Development Tools"
  description: "just - Command runner similar to make"

pinentry-mac:
  category: "Security"
  description: "pinentry-mac - PIN entry dialog for macOS"

mactop:
  category: "System Monitoring"
  description: "mactop - Apple Silicon performance monitor"

mergiraf:
  category: "Development Tools"
  description: "mergiraf - Smart Git merge conflict resolver"

mkcert:
  category: "Development Tools"
  description: "mkcert - Local SSL certificate generator"

nss:
  category: "Security"
  description: "NSS - Network Security Services libraries"

thefuck:
  category: "Shell Utilities"
  description: "thefuck - Corrects errors in previous console commands"

fzf:
  category: "Shell Utilities"
  description: "fzf - Fuzzy finder for command line"

navi:
  category: "Shell Utilities"
  description: "navi - Interactive cheatsheet tool"

jq:
  category: "Text Processing"
  description: "jq - JSON processor for command line"

yadm:
  category: "Development Tools"
  description: "yadm - Yet Another Dotfiles Manager"

tmate:
  category: "Terminal Utilities"
  description: "tmate - Instant terminal sharing"

tmux:
  category: "Terminal Utilities"
  description: "tmux - Terminal multiplexer"

watch:
  category: "System Utilities"
  description: "watch - Execute program periodically"

openssl@3:
  category: "Security"
  description: "OpenSSL 3 - Cryptography and SSL/TLS toolkit"

skhd:
  category: "Keyboard Tools"
  description: "skhd - Simple hotkey daemon for macOS"

imagemagick:
  category: "Image Processing"
  description: "ImageMagick - Image manipulation tools"

mas:
  category: "System Utilities"
  description: "mas - Mac App Store command line interface"

gh:
  category: "Development Tools"
  description: "gh - GitHub command line tool"

glab:
  category: "Development Tools"
  description: "glab - GitLab command line tool"

node:
  category: "Programming Languages"
  description: "Node.js - JavaScript runtime"

php@8.2:
  category: "Programming Languages"
  description: "PHP 8.2 - Server-side scripting language"

golang:
  category: "Programming Languages"
  description: "Go - Programming language by Google"

gitleaks:
  category: "Security"
  description: "Gitleaks - Scan git repos for secrets"

uv:
  category: "Programming Languages"
  description: "uv - Fast Python package installer"

yarn:
  category: "Package Managers"
  description: "Yarn - JavaScript package manager"

yarn-completion:
  category: "Shell Utilities"
  description: "Yarn completion - Shell completion for Yarn"
