set allow-duplicate-recipes := true
set ignore-comments := true

_default:
    #!/usr/bin/env bash
    source /opt/sparkdock/sjust/libs/libformatting.sh
    source /opt/sparkdock/sjust/libs/libcolors.sh
    echo "${bold}${cyan}Welcome to SparkJust${normal} - ${green}this is a tool to automate some useful tasks.${normal}"
    echo
    echo "$(Urllink "https://github.com/sparkfabrik/sparkdock" "Click here to view the Sparkdock sjust documentation")"
    echo
    /usr/local/bin/sjust --list --list-heading $'Available commands:\n' --list-prefix $' - '

# Imports
import "/opt/sparkdock/sjust/recipes/00-default.just"

# this is optional and let the user to add custom tasks.
import? "~/.config/sjust/100-custom.just"