set allow-duplicate-recipes := true
set ignore-comments := true

docker_settings_file := "${HOME}/Library/Group Containers/group.com.docker/settings-store.json"

_default:
    #!/usr/bin/env bash
    source /opt/sparkdock/sjust/libs/libformatting.sh
    source /opt/sparkdock/sjust/libs/libcolors.sh
    echo "${bold}${cyan}Welcome to SparkJust${normal} - ${green}this is a tool to automate some useful tasks.${normal}"
    echo
    echo "👉 Remember you can add your own tasks in ~/.config/sjust/100-custom.just"
    echo
    echo "$(Urllink "https://just.systems/man/en/" "click here to view the Just documentation")"
    echo
    /usr/local/bin/sjust --list --list-heading $'Available commands:\n' --list-prefix $' - '

# Imports
import "/opt/sparkdock/sjust/recipes/_private.just"
import "/opt/sparkdock/sjust/recipes/00-default.just"
import "/opt/sparkdock/sjust/recipes/01-lima.just"
import "/opt/sparkdock/sjust/recipes/02-docker-desktop.just"
import "/opt/sparkdock/sjust/recipes/03-macos-defaults.just"

# this is optional and let the user to add custom tasks.
import? "~/.config/sjust/100-custom.just"