blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://github.com/sparkfabrik/sparkdock/blob/master/README.md
    about: Check the documentation for usage instructions and configuration details
  - name: 🔧 Troubleshooting Guide
    url: https://github.com/sparkfabrik/sparkdock/blob/master/TROUBLESHOOTING.md
    about: Common issues and solutions for Sparkdock
  - name: 📖 SparkFabrik Playbook
    url: http://playbook.sparkfabrik.com/guides/local-development-environment-configuration
    about: Company playbook with additional guides and best practices
