---
- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root

- name: Import playbook for macOS
  import_playbook: macos/macos/base.yml
  when: ansible_distribution_version | regex_search('^(1[2-5]\.[0-9]+)')
