---
- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root

- name: Importing Ubuntu 20+
  import_playbook: ubuntu/ubuntu20.yml
  when: ansible_distribution_major_version|int >= 18
