---
- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root

- name: Importing Ubuntu 16-
  import_playbook: ubuntu/ubuntu16.yml
  when: ansible_distribution_major_version|int <= 16
- name: Importing Ubuntu 17+
  import_playbook: ubuntu/ubuntu18.yml
  when: ansible_distribution_major_version|int >= 17
- name: Importing Ubuntu 20+
  import_playbook: ubuntu/ubuntu20.yml
  when: ansible_distribution_major_version|int >= 18
