---
- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root

- include: ubuntu/ubuntu16.yml
  when: ansible_distribution_major_version <= '16'
- include: ubuntu/ubuntu18.yml
  when: ansible_distribution_major_version >= '17'