---
# macOS System Defaults Configuration
# Inspired by Jeff Geerling's dotfiles and mac-dev-playbook
# Optimized for developer productivity and workflow

# General UI/UX improvements
- name: Expand save panel by default
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true
  tags: macos-defaults

- name: Expand print panel by default
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: true
  tags: macos-defaults

- name: Save to disk (not to iCloud) by default
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
  tags: macos-defaults

- name: Disable automatic capitalization
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: false
  tags: macos-defaults

- name: Disable smart dashes
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
  tags: macos-defaults

- name: Disable automatic period substitution
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    type: bool
    value: false
  tags: macos-defaults

- name: Disable smart quotes
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
  tags: macos-defaults

- name: Disable auto-correct
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
  tags: macos-defaults

# Keyboard and input settings for developers
- name: Set faster key repeat rate
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 1
  tags: macos-defaults

- name: Set shorter delay until key repeat
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 10
  tags: macos-defaults

- name: Disable press-and-hold for keys in favor of key repeat
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
  tags: macos-defaults

# Trackpad settings
- name: Enable tap to click for trackpad
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: bool
    value: true
  tags: macos-defaults

- name: Enable secondary click on trackpad
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadRightClick
    type: bool
    value: true
  tags: macos-defaults

- name: Map trackpad bottom right corner to right-click
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadCornerSecondaryClick
    type: int
    value: 2
  tags: macos-defaults

# Finder improvements for developers
- name: Show all filename extensions in Finder
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
  tags: macos-defaults

- name: Show hidden files in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
  tags: macos-defaults

- name: Show status bar in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
  tags: macos-defaults

- name: Show path bar in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
  tags: macos-defaults

- name: Display full POSIX path as Finder window title
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true
  tags: macos-defaults

- name: Keep folders on top when sorting by name
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true
  tags: macos-defaults

- name: When performing a search, search the current folder by default
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "SCcf"
  tags: macos-defaults

- name: Disable warning when changing a file extension
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
  tags: macos-defaults

- name: Avoid creating .DS_Store files on network or USB volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
  tags: macos-defaults

- name: Avoid creating .DS_Store files on USB volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true
  tags: macos-defaults

- name: Use list view in all Finder windows by default
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "Nlsv"
  tags: macos-defaults

# Dock improvements
- name: Set the icon size of Dock items
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 48
  tags: macos-defaults

- name: Change minimize/maximize window effect to scale
  community.general.osx_defaults:
    domain: com.apple.dock
    key: mineffect
    type: string
    value: "scale"
  tags: macos-defaults

- name: Minimize windows into their application's icon
  community.general.osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true
  tags: macos-defaults

- name: Enable spring loading for all Dock items
  community.general.osx_defaults:
    domain: com.apple.dock
    key: enable-spring-load-actions-on-all-items
    type: bool
    value: true
  tags: macos-defaults

- name: Show indicator lights for open applications in the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: true
  tags: macos-defaults

- name: Don't animate opening applications from the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: launchanim
    type: bool
    value: false
  tags: macos-defaults

- name: Automatically hide and show the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  tags: macos-defaults

- name: Remove the auto-hiding Dock delay
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
  tags: macos-defaults

- name: Remove the animation when hiding/showing the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: 0
  tags: macos-defaults

- name: Don't show recent applications in Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: false
  tags: macos-defaults

# Safari developer settings
- name: Enable Safari's developer menu
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: IncludeInternalDebugMenu
    type: bool
    value: true
  tags: macos-defaults

- name: Enable Safari Developer menu
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: IncludeDevelopMenu
    type: bool
    value: true
  tags: macos-defaults

- name: Enable Safari Web Inspector
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: WebKitDeveloperExtrasEnabledPreferenceKey
    type: bool
    value: true
  tags: macos-defaults

# Enable Safari Web Inspector for WebKit2/Safari (modern engine)
- name: Enable Safari Web Inspector (WebKit2)
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: WebKitDeveloperExtras
    type: bool
    value: true
  tags: macos-defaults

- name: Show the full URL in the address bar
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: ShowFullURLInSmartSearchField
    type: bool
    value: true
  tags: macos-defaults

- name: Prevent Safari from opening 'safe' files automatically after downloading
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: AutoOpenSafeDownloads
    type: bool
    value: false
  tags: macos-defaults

- name: Enable Safari's status bar
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: ShowStatusBar
    type: bool
    value: true
  tags: macos-defaults

# Terminal improvements
- name: Only use UTF-8 in Terminal.app
  community.general.osx_defaults:
    domain: com.apple.terminal
    key: StringEncodings
    type: array
    value:
      - 4
  tags: macos-defaults

- name: Enable Secure Keyboard Entry in Terminal.app
  community.general.osx_defaults:
    domain: com.apple.terminal
    key: SecureKeyboardEntry
    type: bool
    value: true
  tags: macos-defaults

# TextEdit improvements for developers
- name: Use plain text mode for new TextEdit documents
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: RichText
    type: int
    value: 0
  tags: macos-defaults

- name: Open and save files as UTF-8 in TextEdit
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: PlainTextEncoding
    type: int
    value: 4
  tags: macos-defaults

- name: Save files as UTF-8 in TextEdit
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: PlainTextEncodingForWrite
    type: int
    value: 4
  tags: macos-defaults

# Activity Monitor improvements
- name: Show the main window when launching Activity Monitor
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: OpenMainWindow
    type: bool
    value: true
  tags: macos-defaults

- name: Visualize CPU usage in the Activity Monitor Dock icon
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: IconType
    type: int
    value: 5
  tags: macos-defaults

- name: Show all processes in Activity Monitor
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: ShowCategory
    type: int
    value: 0
  tags: macos-defaults

- name: Sort Activity Monitor results by CPU usage
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortColumn
    type: string
    value: "CPUUsage"
  tags: macos-defaults

- name: Sort Activity Monitor results in descending order
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortDirection
    type: int
    value: 0
  tags: macos-defaults

# Screenshots improvements
- name: Save screenshots to the desktop
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{ ansible_env.HOME }}/Desktop"
  tags: macos-defaults

- name: Save screenshots in PNG format
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: "png"
  tags: macos-defaults

- name: Disable shadow in screenshots
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true
  tags: macos-defaults

# Time Machine improvements
- name: Prevent Time Machine from prompting to use new hard drives as backup volume
  community.general.osx_defaults:
    domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    type: bool
    value: true
  tags: macos-defaults

# Disk Utility improvements
- name: Enable the debug menu in Disk Utility
  community.general.osx_defaults:
    domain: com.apple.DiskUtility
    key: DUDebugMenuEnabled
    type: bool
    value: true
  tags: macos-defaults

- name: Enable the advanced image options in Disk Utility
  community.general.osx_defaults:
    domain: com.apple.DiskUtility
    key: advanced-image-options
    type: bool
    value: true
  tags: macos-defaults

# Restart affected applications to apply changes
- name: Restart Finder to apply changes
  command: killall Finder
  ignore_errors: true
  tags: macos-defaults

- name: Restart Dock to apply changes
  command: killall Dock
  ignore_errors: true
  tags: macos-defaults

- name: Restart Safari to apply changes
  command: killall Safari
  ignore_errors: true
  tags: macos-defaults

- name: Restart Activity Monitor to apply changes
  command: killall "Activity Monitor"
  ignore_errors: true
  tags: macos-defaults