name: Test Ansible Playbook

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Sparkdock using installation script
        run: |
          # Modify the script to run non-interactively and skip any prompts
          sed -i '' 's/--ask-become-pass/-e "ansible_become_password=" --become/g' ./bin/sparkdock.macos

          # Make the script executable
          chmod +x ./bin/install.macos
          chmod +x ./bin/sparkdock.macos
          chmod +x ./bin/common/utils.sh

          # Run the installation script with sudo access
          sudo mkdir -p /opt/sparkdock
          sudo chown -R $(whoami) /opt/sparkdock

          # Install Sparkdock to /opt/sparkdock
          cp -R ./* /opt/sparkdock/

          # Run the modified installation script
          /opt/sparkdock/bin/sparkdock.macos skip-update

      - name: Verify installations
        run: |
          echo "Verifying key installations..."
          brew list | grep docker || echo "Docker not found"
          brew list | grep kubernetes-cli || echo "kubectl not found"
          brew list | grep google-cloud-sdk || echo "gcloud not found"
          brew list | grep awscli || echo "aws not found"

          echo "Test completed on ${{ matrix.os }}"

      - name: Clean up test installations (optional)
        if: always()
        run: |
          echo "Cleaning up..."
          sudo rm -rf /opt/sparkdock
